# Generated by Django 3.2.5 on 2021-07-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('s_no', models.IntegerField()),
                ('rc_number', models.CharField(max_length=50)),
                ('scheme', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('receipt_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('kejriwal_wheat', models.FloatField()),
                ('kejriwal_rice', models.FloatField()),
                ('kejriwal_sugar', models.FloatField()),
                ('pm_wheat', models.FloatField()),
                ('pm_rice', models.FloatField()),
                ('amount', models.FloatField()),
                ('portability', models.CharField(max_length=50)),
                ('auth_time', models.FloatField()),
            ],
        ),
    ]
